version: "3.9"

services:
  theatre-db:
    image: postgres:14
    container_name: theatre-db
    restart: always
    volumes:
      - content_db:/var/lib/postgresql/data/
      - ./01_schema_design/movies_database.ddl:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    env_file:
      - ./.env

volumes:
  content_db:
